Update patch set 5
Patch Set 5:

ERROR: /home/jorge/cm13/packages/providers/DownloadProvider/ui/src/com/android/providers/downloads/ui/TrampolineActivity.java:86: The method pauseDownload(long) is undefined for the type DownloadManager
ERROR: /home/jorge/cm13/packages/providers/DownloadProvider/ui/src/com/android/providers/downloads/ui/TrampolineActivity.java:93: PAUSED_BY_MANUAL cannot be resolved or is not a field
ERROR: /home/jorge/cm13/packages/providers/DownloadProvider/ui/src/com/android/providers/downloads/ui/TrampolineActivity.java:95: The method resumeDownload(long) is undefined for the type DownloadManager
target Pack Relocations: libnfc_nci_jni (/home/jorge/cm13/out/target/product/bacon/obj/SHARED_LIBRARIES/libnfc_nci_jni_intermediates/PACKED/libnfc_nci_jni.so)
INFO: Compaction                 : 8192 bytes
build/core/java.mk:643: recipe for target '/home/jorge/cm13/out/target/common/obj/APPS/DownloadProviderUi_intermediates/with-local/classes.dex' failed
make: *** [/home/jorge/cm13/out/target/common/obj/APPS/DownloadProviderUi_intermediates/with-local/classes.dex] Error 41
make: *** Waiting for unfinished jobs....
Building with Jack: /home/jorge/cm13/out/target/common/obj/APPS/PhotoPhase_intermediates/with-local/classes.dex
target Pack Relocations: libpac (/home/jorge/cm13/out/target/product/bacon/obj/SHARED_LIBRARIES/libpac_intermediates/PACKED/libpac.so)

This commit broke cm build. Maybe something is missing to be added?

Patch-set: 5
Reviewer: Jorge Ayres Pereira <11227@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0